name: ci_2_daft_fm

on:
  workflow_run:
    branches:
      - staging
    workflows:
      - build_staging_daft_fm
    types:
      - completed
  workflow_dispatch:

jobs:
  ci_2_daft_fm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [self-hosted]
        node: [20]

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - name: sitespeed.io (staging.)
        run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:35.5.0 https://staging.daft.fm --budget.configPath .github/budget.json -n 3 --axe.enable
